name: CI

on:
  pull_request:
    branches: [ main ]
  workflow_call:

permissions:
    contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Set up uv
      uses: astral-sh/setup-uv@v5

    - name: Install dependencies
      run: uv sync

    - name: Run ruff linter
      run: uv run ruff check --output-format=github .

    - name: Run ruff format check
      run: uv run ruff format --check .

    - name: Run mypy
      run: uv run mypy .
